theme = "hugo-universal-theme"
languageCode = "es-mx"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "es"

[Languages]
[Languages.en]
baseurl = "https://example.en"
title = "Our blog"
weight = 1

[Languages.es]
baseurl = "https://example.es"
title = "Nuestro Blog"
weight = 2


# Enable comments by entering your Disqus shortname
disqusShortname = "Arteko"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 2

[menu]

# Main menu

[[menu.main]]
    name = "menuHome"
    url  = "https://cuby.mx/"
    weight = 1

[[menu.main]]
    name = "menuBlog"
    url  = "/"
    weight = 2

[[menu.main]]
    name = "menuInfo"
    url  = "/informacion"
    weight = 3

[[menu.main]]
    name = "menuSupport"
    url  = "/soporte"
    weight = 4

[[menu.main]]
    name = "menuBuy"
    url  = "/comprar"
    weight = 5

# Top bar social links menu

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    copyright = "© 2018 Arteko Electronics SA de CV. Todos los derechos reservados"

    # Format dates with Go's time formatting
    date_format = "2 Jan 2006"

    logo = "img/logo.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
